# Generated by Django 5.0.6 on 2024-06-16 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="room",
            old_name="votes_skip",
            new_name="votes_to_skip",
        ),
    ]
